export interface CatalogApp {
  id: string;
  name: string;
  icon: string;
  description: string;
  category: "media" | "productivity" | "utilities" | "monitoring" | "storage";
  dockerImage: string;
  defaultPort: number;
  containerName: string;
  color: string;
  volumes?: string[];
  envVars?: string[];
  manualInstall?: boolean;
}

export const CATALOG: CatalogApp[] = [
  {
    id: "navidrome",
    name: "Navidrome",
    icon: "🎵",
    description: "Modern music server and streamer compatible with Subsonic API.",
    category: "media",
    dockerImage: "deluan/navidrome",
    defaultPort: 4533,
    containerName: "navidrome",
    color: "#9c36b5",
    volumes: ["/DATA/AppData/navidrome/data:/data", "/DATA/AppData/navidrome/music:/music:ro"],
    envVars: ["ND_SCANSCHEDULE=1h", "ND_LOGLEVEL=info"],
  },
  {
    id: "pihole",
    name: "Pi-hole",
    icon: "🛡️",
    description: "Network-wide ad blocker acting as a DNS sinkhole.",
    category: "utilities",
    dockerImage: "pihole/pihole",
    defaultPort: 8080,
    containerName: "pihole",
    color: "#c92a2a",
    volumes: ["/DATA/AppData/pihole/etc:/etc/pihole", "/DATA/AppData/pihole/dnsmasq:/etc/dnsmasq.d"],
    envVars: ["WEBPASSWORD=admin", "TZ=Asia/Kolkata"],
  },
  {
    id: "memos",
    name: "Memos",
    icon: "📝",
    description: "Lightweight, self-hosted memo hub for quick notes.",
    category: "productivity",
    dockerImage: "neosmemo/memos",
    defaultPort: 5230,
    containerName: "memos",
    color: "#5c7cfa",
    volumes: ["/DATA/AppData/memos:/var/opt/memos"],
  },
  {
    id: "filebrowser",
    name: "File Browser",
    icon: "📁",
    description: "Web-based file manager for browsing and managing your files.",
    category: "utilities",
    dockerImage: "filebrowser/filebrowser",
    defaultPort: 8081,
    containerName: "filebrowser",
    color: "#f76707",
    volumes: ["/DATA:/srv", "/DATA/AppData/filebrowser/database.db:/database.db"],
  },
  {
    id: "portainer",
    name: "Portainer",
    icon: "🐋",
    description: "Lightweight container management UI for Docker.",
    category: "monitoring",
    dockerImage: "portainer/portainer-ce",
    defaultPort: 9000,
    containerName: "portainer",
    color: "#1971c2",
    volumes: ["/var/run/docker.sock:/var/run/docker.sock", "/DATA/AppData/portainer:/data"],
  },
  {
    id: "uptime-kuma",
    name: "Uptime Kuma",
    icon: "📡",
    description: "Self-hosted uptime monitoring tool with a fancy UI.",
    category: "monitoring",
    dockerImage: "louislam/uptime-kuma",
    defaultPort: 3001,
    containerName: "uptime-kuma",
    color: "#2f9e44",
    volumes: ["/DATA/AppData/uptime-kuma:/app/data"],
  },
  {
    id: "homeassistant",
    name: "Home Assistant",
    icon: "🏠",
    description: "Open source home automation platform.",
    category: "utilities",
    dockerImage: "homeassistant/home-assistant",
    defaultPort: 8123,
    containerName: "homeassistant",
    color: "#1a73e8",
    volumes: ["/DATA/AppData/homeassistant:/config"],
    envVars: ["TZ=Asia/Kolkata"],
  },
  {
    id: "jellyfin",
    name: "Jellyfin",
    icon: "🎬",
    description: "Free software media system to manage and stream your media.",
    category: "media",
    dockerImage: "jellyfin/jellyfin",
    defaultPort: 8096,
    containerName: "jellyfin",
    color: "#7950f2",
    volumes: ["/DATA/AppData/jellyfin/config:/config", "/DATA/AppData/jellyfin/cache:/cache", "/DATA/AppData/media:/media:ro"],
  },
  {
    id: "vaultwarden",
    name: "Vaultwarden",
    icon: "🔐",
    description: "Unofficial Bitwarden-compatible server written in Rust.",
    category: "productivity",
    dockerImage: "vaultwarden/server",
    defaultPort: 8222,
    containerName: "vaultwarden",
    color: "#495057",
    volumes: ["/DATA/AppData/vaultwarden:/data"],
  },
  {
    id: "dashdot",
    name: "Dash.",
    icon: "📊",
    description: "Modern server dashboard with live system metrics.",
    category: "monitoring",
    dockerImage: "mauricenino/dashdot",
    defaultPort: 3005,
    containerName: "dashdot",
    color: "#e64980",
    volumes: ["/proc:/mnt/host/proc:ro", "/sys:/mnt/host/sys:ro"],
  },
  {
    id: "mealie",
    name: "Mealie",
    icon: "🍽️",
    description: "Self-hosted recipe manager and meal planner.",
    category: "productivity",
    dockerImage: "hkotel/mealie",
    defaultPort: 9925,
    containerName: "mealie",
    color: "#12b886",
    volumes: ["/DATA/AppData/mealie:/app/data"],
  },
  {
    id: "gitea",
    name: "Gitea",
    icon: "🐙",
    description: "Lightweight self-hosted Git service.",
    category: "productivity",
    dockerImage: "gitea/gitea",
    defaultPort: 3030,
    containerName: "gitea",
    color: "#2f9e44",
    volumes: ["/DATA/AppData/gitea:/data"],
    envVars: ["USER_UID=1000", "USER_GID=1000"],
  },
  {
    id: "dozzle",
    name: "Dozzle",
    icon: "🪵",
    description: "Realtime log viewer for Docker containers.",
    category: "monitoring",
    dockerImage: "amir20/dozzle",
    defaultPort: 9999,
    containerName: "dozzle",
    color: "#e03131",
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"],
  },
  {
    id: "btop",
    name: "Btop",
    icon: "📈",
    description: "Resource monitor showing usage for CPU, RAM, disks, and network.",
    category: "monitoring",
    dockerImage: "ghcr.io/bigbeartechworld/big-bear-btop",
    defaultPort: 57575,
    containerName: "big-bear-btop",
    color: "#495057",
    volumes: ["/proc:/host/proc:ro", "/sys:/host/sys:ro"],
  },
  {
    id: "immich",
    name: "Immich",
    icon: "📷",
    description: "High-performance self-hosted photo and video backup solution.",
    category: "media",
    dockerImage: "ghcr.io/immich-app/immich-server",
    defaultPort: 2283,
    containerName: "immich_server",
    color: "#1971c2",
    manualInstall: true,
  },
];

export function getCatalogApp(id: string): CatalogApp | undefined {
  return CATALOG.find((a) => a.id === id);
}
