apiVersion: v1
kind: Service
metadata:
  name: taraos
  namespace: taraos
  labels:
    app: taraos
spec:
  selector:
    app: taraos
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
