image:
  repository: louislam/uptime-kuma
  tag: latest
service:
  port: 3001
  nodePort: 30401
storage:
  enabled: true
  hostPath: /DATA/AppData/uptime-kuma
  mountPath: /app/data
  size: 1Gi
env: []
