image:
  repository: mauricenino/dashdot
  tag: latest
service:
  port: 3001
  nodePort: 30305
storage:
  enabled: false
  mountPath: /data
  size: 1Gi
env:
  - name: DASHDOT_ENABLE_CPU_TEMPS
    value: "true"
