image:
  repository: ghcr.io/mealie-recipes/mealie
  tag: latest
service:
  port: 9000
  nodePort: 30925
storage:
  enabled: true
  hostPath: /DATA/AppData/mealie
  mountPath: /app/data
  size: 1Gi
env:
  - name: ALLOW_SIGNUP
    value: "true"
  - name: TZ
    value: Asia/Kolkata
