image:
  repository: vaultwarden/server
  tag: latest
service:
  port: 80
  nodePort: 30222
storage:
  enabled: true
  hostPath: /DATA/AppData/vaultwarden
  mountPath: /data
  size: 1Gi
env:
  - name: WEBSOCKET_ENABLED
    value: "true"
